# Welcome to Jekyll!
#

# Site settings
pagetitle: LUCAS Diététique
title: Edwin Lucas
subtitle: Diététicien nutritionniste diplômé
description: |
  Éducation nutritionnelle et suivi diététique,
  chrononutrition, micronutrition, coaching sportif

  Toulouse
owner: Edwin Lucas # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: lucas.edwin1@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucas-dietetique.fr" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/LUCAS-Edwin-di%C3%A9t%C3%A9ticien-nutritionniste-coaching-sportif-366820396857005
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
